/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ugp_nativeShadow */

#ifndef _Included_com_example_ugp_nativeShadow
#define _Included_com_example_ugp_nativeShadow
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ugp_nativeShadow
 * Method:    getShadow
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jint JNICALL Java_com_example_ugp_nativeShadow_getShadow
  (JNIEnv *, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
